<template>
  <div class="q-pa-md">
    <TableCustom
      class-name="table-sticky-header-column-table"
      flat
      bordered
      title="Order History"
      :rows="rows"
      :columns="columns"
      row-key="id"
      styles="height: 500px"
    />
  </div>
</template>

<script setup lang="ts">
import type { QTableColumn } from 'quasar'
import { convertToUSDate } from 'src/helpers/convertToUSDate'
import { convertWithCommas } from 'src/helpers/convertWithCommas'
import TableCustom from 'src/components/TableCustom/TableCustom.vue'

const columns: QTableColumn[] = [
  {
    name: 'options',
    required: true,
    label: 'Options',
    align: 'left',
    field: 'options',
    // format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'inv',
    required: true,
    label: 'Inv#',
    align: 'left',
    field: 'inv',
    // format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'cardType',
    required: true,
    label: 'Card Type',
    align: 'left',
    field: 'cardType',
    // format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'createdAt',
    required: true,
    label: 'Posted on',
    align: 'left',
    field: 'createdAt',
    format: (processed: string) => convertToUSDate(processed),
    sortable: true,
  },
  {
    name: 'processedOn',
    required: true,
    label: 'Processed On',
    align: 'left',
    field: 'processedOn',
    format: (processed: string) => convertToUSDate(processed),
    sortable: true,
  },
  {
    name: 'nameCard',
    required: true,
    label: 'Name on Card',
    align: 'left',
    field: 'nameCard',
    // format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'submittedBy',
    required: true,
    label: 'Submitted By',
    align: 'left',
    field: 'submittedBy',
    // format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'chargeAmount',
    required: true,
    label: 'Charge Amount',
    align: 'left',
    field: 'chargeAmount',
    format: (amount: number) => `$${convertWithCommas(amount)}`,
    sortable: true,
  },
  {
    name: 'paidAmount',
    required: true,
    label: 'Paid Amount',
    align: 'left',
    field: 'paidAmount',
    format: (amount: number) => `$${convertWithCommas(amount)}`,
    sortable: true,
  },
  {
    name: 'balanceDue',
    required: true,
    label: 'Balance Due',
    align: 'left',
    field: 'balanceDue',
    format: (amount: number) => `$${convertWithCommas(amount)}`,
    sortable: true,
  },
]

const rows = [
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
  {
    id: 1,
    options: 'Email Receipts',
    inv: '571921',
    cardType: 'Invoice',
    createdAt: new Date(),
    processedOn: new Date(),
    nameCard: 'Jane Cohen',
    submittedBy: 'James Doe',
    chargeAmount: 10,
    paidAmount: 15,
    balanceDue: 15,
  },
]
</script>

<style lang="scss">
@import './OrderHistoryTable.scss';
</style>
