import type { MemberInterface } from "src/modules/dashboard/interfaces/member-interfaces";


export const members: MemberInterface[] = [
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
  {
    id: 1,
    lastName: 'Blumenfeld',
    firstName: 'Jane',
    spouse: 'Jhon',
    title: 'Mrs',
    address: '245 Central Park South',
    city: 'New York',
    zipCode: '10019',
    phone: '201-345-6789',
    email: 'test@EmailStatsPage.com',
    code: 'UTWMY-COLDS',
    misc: '11826269',
    dateAdded: new Date()
  },
]
